CREATE DATABASE QLKS
USE QLKS
set dateformat DMY

CREATE TABLE LOAIPHONG (
    MALOAIPHONG nvarchar(10) NOT NULL PRIMARY KEY,
    TENLOAIPHONG NVARCHAR(30) NOT NULL,
    DONGIA INT NOT NULL,
    GHICHU NVARCHAR(100)
)
INSERT INTO LOAIPHONG VALUES('A',150000,'PHÒNG GÀ')
SELECT * FROM LOAIPHONG

CREATE TABLE PHONG (
    MAPHONG INT NOT NULL PRIMARY KEY IDENTITY,
    MALOAIPHONG INT NOT NULL FOREIGN KEY REFERENCES LOAIPHONG(MALOAIPHONG),
    TENPHONG NVARCHAR(20) NOT NULL,
    GHICHU NVARCHAR(100) NOT NULL,
	TINHTRANG INT NOT NULL,
)

ALTER TABLE	CHITIETBCDT DROP CONSTRAINT FK__CHITIETBC__MALOA__5535A963
ALTER TABLE	LOAIPHONG DROP CONSTRAINT PK__LOAIPHON__82203A7630F09564
ALTER TABLE	LOAIPHONG 
ALTER COLUMN MALOAIPHONG NVARCHAR(10) --1 LA CO NGUOI , 0 LA KHONG NGUOI
delete from PHONG
INSERT INTO PHONG VALUES(1,'101','NONE',1)
INSERT INTO PHONG VALUES(1,'102','NONE',0)
INSERT INTO PHONG VALUES(1,'103','NONE',1)
INSERT INTO PHONG VALUES(1,'104','NONE',1)


SELECt * from PHONG
select * from dbo.PHONG WHERE TINHTRANG = 1 

SELECT * FROM CHITIETHOADON,KHACHHANG,HOADON WHERE (KHACHHANG.MAKHACHHANG=HOADON.MAKHACHHANG) AND (HOADON.MAHOADON=CHITIETHOADON.MAHOADON) AND (HOADON.TINHTRANGHOADON=0) AND KHACHHANG.MAKHACHHANG=

select * from KHACHHANG


CREATE TABLE LOAIKHACHHANG (
    MALOAIKHACHHANG INT NOT NULL PRIMARY KEY IDENTITY,
    TENLOAIKHACHHANG NVARCHAR(50) NOT NULL
)
insert into LOAIKHACHHANG VALUES ('NOI DIA')
insert into LOAIKHACHHANG VALUES ('NUOC NGOAI')
SELECT * FROM LOAIKHACHHANG

CREATE TABLE KHACHHANG (
    MAKHACHHANG INT NOT NULL PRIMARY KEY IDENTITY,
    MALOAIKHACHHANG INT NOT NULL FOREIGN KEY REFERENCES LOAIKHACHHANG(MALOAIKHACHHANG),
    TENKHACHHANG NVARCHAR(50) NOT NULL,
    CMND INT NOT NULL,
    DIACHI NVARCHAR(50) NOT NULL,
    SODIENTHOAI INT,
    NGAYSINH DATETIME
)
SELECT TENKHACHHANG FROM KHACHHANG

insert into KHACHHANG VALUES (2, 'NGUYEN VAN ASDGF', 1243123,'ASDFASDF',122323,'01/01/2000')
insert into KHACHHANG VALUES (2, 'NGUYEN VAN ASDGF', 1243123,'ASDFASDF',122323,'01/01/2000')
insert into KHACHHANG VALUES (2, 'NGUYEN VAN b', 1243123,'ASDagdfhjadsfgFASDF',122323,'01/01/2000')

insert into KHACHHANG VALUES (1, 'NGUYEN VAN A', 1243123,'ASDFASDF',72316476,01/01/20)
SELECT * FROM KHACHHANG
DELETE  
FROM KHACHHANG
WHERE MAKHACHHANG=3




CREATE TABLE PHIEUTHUEPHONG (
    MAPHIEUTHUE INT NOT NULL PRIMARY KEY IDENTITY,
    NGAYLAPPHIEU DATETIME NOT NULL,
    MAPHONG INT NOT NULL FOREIGN KEY REFERENCES PHONG(MAPHONG)
)
insert PHIEUTHUEPHONG(NGAYLAPPHIEU,MAPHONG) VALUES ('27/06/2020',2)
insert PHIEUTHUEPHONG(NGAYLAPPHIEU,MAPHONG) VALUES ('27/06/2020',3)
SELECT * FROM PHIEUTHUEPHONG

CREATE TABLE CHITIETPHIEUTHUEPHONG (
    MACHITIETPHIEUTHUE INT NOT NULL PRIMARY KEY IDENTITY,
	MAPHIEUTHUE INT NOT NULL FOREIGN KEY REFERENCES PHIEUTHUEPHONG(MAPHIEUTHUE),
    MAKHACHHANG INT NOT NULL FOREIGN KEY REFERENCES KHACHHANG(MAKHACHHANG)
)
insert CHITIETPHIEUTHUEPHONG(MAPHIEUTHUE,MAKHACHHANG) VALUES (6,1)
insert CHITIETPHIEUTHUEPHONG(MAPHIEUTHUE,MAKHACHHANG) VALUES (6,2)
SELECT * FROM CHITIETPHIEUTHUEPHONG







CREATE TABLE THAMSO (
    SOLUONGKHACHTOIDATRONGPHONG INT NOT NULL
)


CREATE TABLE DANGKI (
    MADANGKI INT NOT NULL PRIMARY KEY IDENTITY,
    TENDANGNHAP VARCHAR(50) NOT NULL,
	MATKHAU VARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	SODIENTHOAI INT NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL
)
ALTER TABLE THAMSO ADD PHUTHU VARCHAR(50)

ALTER TABLE THAMSO ADD HESO FLOAT

CREATE TABLE HOADON (
    MAHOADON INT NOT NULL PRIMARY KEY IDENTITY,
    THANHTIEN INT NOT NULL,
    NGAYLAP DATETIME,
	MAKHACHHANG INT REFERENCES KHACHHANG(MAKHACHHANG)
)


SELECT * FROM HOADON

ALTER proc USP_InsertBill
@makh int
as
begin
	insert into HOADON(NGAYLAP,MAKHACHHANG,THANHTIEN,TINHTRANGHOADON)
	values(GETDATE(),@makh,0,0)
end
go


SELECT * FROM HOADON
select * from KHACHHANG
insert into HOADON(NGAYLAP,MAKHACHHANG,THANHTIEN)
	values(GETDATE(),1,0)

select * from HOADON
INSERT INTO HOADON(NGAYLAP, THANHTIEN,HOTEN, DIACHI) VALUES ('28/07/2020',0, 'NGUYEN VAN B', 'ÁDFASDFASDF')
DELETE HOADON

select max(MAHOADON)  from HOADON

create proc USP_GetUnCheckBillByIDCustomer
@makh int
as
begin
	select * 
	from KHACHHANG kh,HOADON hd
	where  (hd.MAKHACHHANG = kh.MAKHACHHANG) and hd.MAKHACHHANG = @makh and (hd.TINHTRANGHOADON =1)
end
go

CREATE TABLE CHITIETHOADON (
    MACHITIETHOADON INT NOT NULL PRIMARY KEY IDENTITY,
    MAHOADON INT NOT NULL FOREIGN KEY REFERENCES HOADON(MAHOADON),
	MAPHONG INT NOT NULL FOREIGN KEY REFERENCES PHONG(MAPHONG),
	SONGAY FLOAT NOT NULL,
    DONGIA INT NOT NULL,	
)

ALTER TABLE CHITIETHOADON ADD THANHTIEN INT DEFAULT 0
MAHOADON,MAPHONG,SONGAY,DONGIA
CREATE TABLE BAOCAODOANHTHU (
    MABCDT INT NOT NULL PRIMARY KEY IDENTITY,
    THANG INT NOT NULL,
    TONGDOANHTHU INT 
)

CREATE TABLE CHITIETBCDT (
    MACTBCDT INT NOT NULL PRIMARY KEY IDENTITY,
    MABCDT INT NOT NULL FOREIGN KEY REFERENCES BAOCAODOANHTHU(MABCDT),
	MALOAIPHONG INT NOT NULL FOREIGN KEY REFERENCES LOAIPHONG(MALOAIPHONG),
    DOANHTHU INT NOT NULL,
	TYLE VARCHAR 
)


--CREATE PROC USP_themChiTietHoaDon
--@mahd INT , @maphong INT, @songay INT,@ngaylaphoadon datetime, @
--as
--begin
--	SELECT hd.NGAYLAP, ptp.NGAYLAPPHIEU
--	FROM HOADON hd, PHIEUTHUEPHONG ptp 
--	WHERE MAPHONG=@maphong
--	@songay=
--	INSERT INTO CHITIETHOADON(MAHOADON,MAPHONG,) values (@mahd,@maphong,@makh)
--end 


 select datediff(dayofyear,PHIEUTHUEPHONG.NGAYLAPPHIEU, HOADON.NGAYLAP ) FROM PHIEUTHUEPHONG, HOADON, CHITIETPHIEUTHUEPHONG WHERE (MAPHONG=2) AND (CHITIETPHIEUTHUEPHONG.MAPHIEUTHUE=PHIEUTHUEPHONG.MAPHIEUTHUE) AND (CHITIETPHIEUTHUEPHONG.MAKHACHHANG= HOADON.MAKHACHHANG)  
 SELECT * FROM PHONG
 SELECT DATEDIFF (DAYOFYEAR, '12/12/2018', '01/01/2019')

ALTER PROC USP_addChiTietHoaDon
@mahd INT , @maphong INT
AS
BEGIN
	declare  @ngaypht datetime, @ngayhd datetime

	select @ngaypht = pt.NGAYLAPPHIEU
	from PHIEUTHUEPHONG pt, PHONG p
	where pt.MAPHONG=@maphong and(p.MAPHONG=pt.MAPHONG) and (p.TINHTRANG=1)
	
	select @ngayhd= hd.NGAYLAP
	from  HOADON hd
	where hd.MAHOADON=@mahd

	declare @songay int 
	set @songay = 0
	SELECT @songay= datediff(DAYOFYEAR ,@ngaypht , @ngayhd)

	declare @dongia int
	select  @dongia=LOAIPHONG.DONGIA FROM PHONG, LOAIPHONG WHERE (PHONG.MALOAIPHONG=LOAIPHONG.MALOAIPHONG) AND (PHONG.MAPHONG =@maphong)

	declare @thanhtien int
	select @thanhtien=CHITIETHOADON.DONGIA * CHITIETHOADON.SONGAY  FROM CHITIETHOADON,PHONG WHERE(CHITIETHOADON.MAPHONG=PHONG.MAPHONG) AND (CHITIETHOADON.MAPHONG=@maphong)

	insert into CHITIETHOADON(MAHOADON,MAPHONG,SONGAY,DONGIA,THANHTIEN) values ( @mahd , @maphong , @songay , @dongia,@thanhtien)
END

EXEC USP_addChiTietHoaDon 1017 , 6
select * from CHITIETPHIEUTHUEPHONG

select * from CHITIETHOADON

SELECT * FROM CHITIETHOADON

SELECT * FROM HOADON WHERE MAHOADON=1004

SELECT * FROM PHONG

select * from HOADON

SELECT * FROM PHIEUTHUEPHONG

insert PHIEUTHUEPHONG(NGAYLAPPHIEU, MAPHONG) VALUES('20/06/2020', 2 )

insert PHIEUTHUEPHONG(NGAYLAPPHIEU, MAPHONG) VALUES('20/06/2020',  4)

insert PHIEUTHUEPHONG(NGAYLAPPHIEU, MAPHONG) VALUES('20/06/2020',  5)

insert PHIEUTHUEPHONG(NGAYLAPPHIEU, MAPHONG) VALUES('20/06/2020',  6)



SELECT * FROM CHITIETHOADON
--select  from dbo.PHONG,PHIEUTHUEPHONG WHERE TINHTRANG =1 AND(PHIEUTHUEPHONG.MAPHONG=PHONG.MAPHONG)

--select * from dbo.KHACHHANG WHERE MAKHACHHANG = 1

--select MAPHIEUTHUE,NGAYLAPPHIEU,PHONG.MAPHONG from dbo.PHONG,PHIEUTHUEPHONG WHERE TINHTRANG =1 AND(PHIEUTHUEPHONG.MAPHONG=PHONG.MAPHONG) 

SELECT * FROM HOADON 
SELECT * FROM KHACHHANG
select * from CHITIETHOADON
SELECT ct.MAPHONG,ct.SONGAY,ct.DONGIA FROM CHITIETHOADON ct,KHACHHANG,HOADON WHERE (KHACHHANG.MAKHACHHANG=HOADON.MAKHACHHANG) AND (HOADON.MAHOADON=ct.MAHOADON) AND (HOADON.TINHTRANGHOADON=0) AND (KHACHHANG.MAKHACHHANG =1)



select * from khachhang
SELECT * FROM CHITIETHOADON
SELECT CHITIETHOADON.MACHITIETHOADON,CHITIETHOADON.MAHOADON, CHITIETHOADON.MAPHONG, CHITIETHOADON.SONGAY, CHITIETHOADON.DONGIA, CHITIETHOADON.THANHTIEN   FROM CHITIETHOADON,KHACHHANG,HOADON WHERE (KHACHHANG.MAKHACHHANG=HOADON.MAKHACHHANG) AND (HOADON.MAHOADON=CHITIETHOADON.MAHOADON) AND (HOADON.TINHTRANGHOADON=0) AND KHACHHANG.MAKHACHHANG = 1

alter table chitiethoadon alter column songay int


delete from CHITIETHOADON where MACHITIETHOADON=16
select * from CHITIETHOADON
delete from CHITIETHOADON where MACHITIETHOADON=20

 